apiVersion: apps/v1
kind: Deployment
metadata:
 name: kp
spec:
 replicas: 3
 selector:
   matchLabels:
     app: kp
 template:
   metadata:
     labels:
       app: kp
   spec:
     containers:
     - name: kp
       image: nginx:latest
       ports:
       - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: kp
spec:
 selector:
   app: nginx:latest
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
 type: LoadBalancer



